### ISSUE TITLE
Track per test analytics

### ISSUE THREAD

**Issue by DuckDuckWhaleUCSD** [jyu283/tritongrader#10]
Use case: I'm about to release a bug fix and re run autograder, and I would like to know if literally anyone is hitting this bug so I can avoid making an announcement if nobody is affected.

**Comment by jyu283** [comment]
closing: beyond the current scope of this library since states cannot be persisted through different runs of the autograder.

(But on a separate note, the autograder could perhaps be configured to emit a well-formatted output JSON to be used by other observability/dependability tools.)
