### ISSUE TITLE
Illegal ASM check

### ISSUE THREAD

**Issue by DuckDuckWhaleUCSD** [jyu283/tritongrader#14]

**Comment by DuckDuckWhaleUCSD** [comment]
Or rather, allow the autograder to change all points for the assignment after it's done

**Comment by jyu283** [comment]
@DuckDuckWhaleUCSD this is already doable (as I implemented in HW 6), but perhaps a better flag (_e.g._, `zero_if`) or some deduction mechanism can be implemented.
